--[[ ============================================================================================================
	Author: Windy
	Date: September 14, 2021
================================================================================================================= ]]
tBotItemData = {}

tBotItemData.purchaseItemList = {
	npc_dota_hero_axe = {
		'item_magic_stick',
		'item_recipe_magic_wand',
		'item_bracer',
		'item_reaver',
		'item_recipe_overwhelming_blink',
		'item_aghanims_shard',
		'item_recipe_blade_mail_2',
		
		'item_wings_of_haste',
		'item_reaver',
		'item_talisman_of_evasion',
		'item_recipe_heart',
		'item_ultimate_scepter_2',

		'item_vladmir_2',
		'item_moon_shard_datadriven',
		'item_moon_shard_datadriven',
	},
	npc_dota_hero_nevermore = {
		'item_wraith_band',
		
		'item_wings_of_haste',

		'item_hallowed_scepter',
		'item_aghanims_shard',
		'item_ultimate_scepter_2',
		'item_recipe_wasp',
		'item_satanic',
		'item_moon_shard_datadriven',
	},
	npc_dota_hero_bane = {
		'item_branches',
		'item_branches',
		'item_recipe_magic_wand',
		'item_circlet',
		'item_recipe_null_talisman',
		'item_energy_booster',
		'item_void_stone',
		'item_recipe_aether_lens',
		'item_recipe_aether_lens',
		'item_recipe_aether_lens',
		'item_aghanims_shard',
		'item_glimmer_cape',
		'item_soul_booster',
		'item_veil_of_discord',
		'item_recipe_arcane_octarine_core',

		'item_aeon_disk',
		'item_recipe_aeon_pendant',
		'item_dagon_5',
		'item_ultimate_scepter_2',

		'item_wings_of_haste',

		'item_hallowed_scepter',
		'item_sphere_2',
	},
	npc_dota_hero_bounty_hunter = {
		'item_magic_stick',
		'item_recipe_magic_wand',

		'item_wings_of_haste',
		'item_ultimate_scepter_2',
		'item_aghanims_shard',
		'item_wasp',
	},
	npc_dota_hero_bloodseeker = {
		'item_wraith_band',
		'item_wraith_band',

		'item_wings_of_haste',
		'item_recipe_abyssal_blade',
		'item_wasp',
		'item_ultimate_scepter_2',
		'item_aghanims_shard',
		'item_monkey_king_bar_2',
		'item_radiance_2',
	},
	npc_dota_hero_bristleback = {
		'item_eternal_shroud',
		'item_buckler',
		'item_lifesteal',
		'item_blades_of_attack',
		'item_recipe_vladmir',
		'item_aghanims_shard',

		'item_phase_boots',
		'item_arcane_boots',
		'item_tranquil_boots',

		'item_assault',
		'item_ultimate_orb',
		'item_recipe_vladmir_2',

		'item_radiance_2',
		'item_undying_heart',
		'item_ultimate_scepter_2',
		'item_insight_armor',
		'item_moon_shard_datadriven',
		'item_moon_shard_datadriven',
	},
	npc_dota_hero_chaos_knight = {
		'item_wings_of_haste',

		'item_vladmir',
		'item_aghanims_shard',

		'item_ultimate_orb',
		'item_recipe_vladmir_2',

		'item_reaver',
		'item_talisman_of_evasion',
		'item_recipe_heart',
	},
	npc_dota_hero_crystal_maiden = {
		'item_branches',
		'item_branches',
		'item_recipe_magic_wand',
		'item_aghanims_shard',
		'item_veil_of_discord',
		'item_aether_lens_3',
		'item_glimmer_cape',
		'item_soul_booster',
		'item_force_staff',
		'item_ultimate_orb',
		'item_ultimate_orb',
		'item_recipe_arcane_octarine_core',
		'item_magic_scepter',
		'item_wings_of_haste',
		'item_mystic_staff',
		'item_mystic_staff',
		'item_recipe_hallowed_scepter',

		'item_aeon_disk',
		'item_recipe_aeon_pendant',
		'item_sphere_2',
	},
	npc_dota_hero_dazzle = {
		'item_headdress',
		'item_fluffy_hat',
		'item_recipe_holy_locket',
		'item_glimmer_cape',
		'item_ultimate_scepter_2',
		'item_aghanims_shard',
		'item_arcane_octarine_core',

		'item_wings_of_haste',
		
		'item_aeon_disk',
		'item_recipe_aeon_pendant',
		'item_dagon_5',
		'item_sphere_2',
	},
	npc_dota_hero_death_prophet = {
		'item_aghanims_shard',
		'item_octarine_core',
		'item_recipe_arcane_octarine_core',
		'item_wings_of_haste',
		'item_ultimate_scepter_2',
		'item_hallowed_scepter',
		
		'item_skadi',
		'item_moon_shard_datadriven',
		'item_moon_shard_datadriven',
	},
	npc_dota_hero_dragon_knight = {
		'item_phase_boots',
		'item_arcane_boots',
		'item_tranquil_boots',
		'item_ultimate_scepter_2',
		'item_aghanims_shard',
		'item_vladmir_2',
		'item_undying_heart',
		'item_wasp',
		'item_moon_shard_datadriven',
		'item_moon_shard_datadriven',
		'item_overwhelming_blink',
	},
	npc_dota_hero_drow_ranger = {
		'item_quarterstaff',
		'item_wings_of_haste',
		'item_aghanims_shard',
		'item_greater_crit',
		'item_recipe_wasp',
		'item_ultimate_scepter_2',
		'item_monkey_king_bar_2',
		'item_satanic',
		'item_moon_shard_datadriven',
		'item_excalibur',
	},

	npc_dota_hero_earthshaker = {
		'item_aghanims_shard',
		'item_wings_of_haste',

		'item_ultimate_orb',
		'item_ultimate_orb',
		'item_undying_heart',
		'item_reaver',
		'item_recipe_overwhelming_blink',
		'item_arcane_octarine_core',
		'item_insight_armor',
		'item_moon_shard_datadriven',
	},
	npc_dota_hero_jakiro = {
		'item_aghanims_shard',
		'item_glimmer_cape',
		'item_hallowed_scepter',
		'item_arcane_octarine_core',
		'item_ultimate_orb',
		'item_ultimate_orb',
		'item_aeon_disk',
		'item_recipe_aeon_pendant',
		'item_force_staff',
		'item_wings_of_haste',
		'item_dagon_5',
		'item_moon_shard_datadriven',
	},
	npc_dota_hero_juggernaut = {
		'item_branches',
		'item_magic_stick',
		'item_wraith_band',
		'item_wraith_band',
		'item_ring_of_health',
		'item_void_stone',
		'item_broadsword',
		'item_claymore',

		'item_wings_of_haste',

		'item_greater_crit',
		'item_recipe_wasp',

		'item_aghanims_shard',
		'item_moon_shard_datadriven',
	},
	npc_dota_hero_kunkka = {
		'item_wings_of_haste',
		'item_aghanims_shard',
		'item_butterfly',
		'item_recipe_wasp',
		'item_ultimate_scepter_2',
		'item_undying_heart',
		'item_vladmir_2',
		'item_wasp',
	},
	npc_dota_hero_lich = {
		'item_glimmer_cape',
		'item_recipe_aether_lens',
		'item_recipe_aether_lens',
		'item_aghanims_shard',
		'item_soul_booster',
		'item_veil_of_discord',
		'item_recipe_arcane_octarine_core',
		'item_hallowed_scepter',
		'item_aeon_disk',
		'item_recipe_aeon_pendant',
		'item_wings_of_haste',
	},
	npc_dota_hero_lina = {
		'item_aghanims_shard',
		'item_glimmer_cape',
		'item_wings_of_haste',
		'item_ultimate_orb',
		'item_ultimate_orb',
		'item_hallowed_scepter',
		'item_dagon_5',
		'item_arcane_octarine_core',

		'item_aeon_disk',
		'item_recipe_aeon_pendant',
		'item_monkey_king_bar_2',
		'item_moon_shard_datadriven',
	},
	npc_dota_hero_lion = {
		'item_null_talisman',
		'item_glimmer_cape',
		'item_recipe_aether_lens',
		'item_recipe_aether_lens',
		'item_veil_of_discord',
		'item_soul_booster',
		'item_recipe_arcane_octarine_core',

		'item_aghanims_shard',
		'item_hallowed_scepter',
		'item_ultimate_orb',
		'item_ultimate_orb',
		'item_wings_of_haste',
		'item_aeon_disk',
		'item_recipe_aeon_pendant',
	},
	npc_dota_hero_luna = {
		'item_wings_of_haste',

		'item_aghanims_shard',
		'item_greater_crit',
		'item_recipe_wasp',
		'item_vladmir',
		'item_ultimate_orb',
		'item_recipe_vladmir_2',
		'item_ultimate_scepter_2',
		'item_skadi',
	},
	npc_dota_hero_necrolyte = {
		'item_glimmer_cape',
		'item_holy_locket',
		'item_chainmail',
		'item_buckler',
		'item_recipe_guardian_greaves',
		'item_aghanims_shard',
		'item_radiance_2',
		'item_ultimate_orb',
		'item_ultimate_orb',
		'item_dagon_5',
		'item_aeon_disk',
		'item_recipe_aeon_pendant',
		'item_arcane_octarine_core',
		'item_hallowed_scepter',
	},
	npc_dota_hero_omniknight = {
		'item_magic_wand',
		'item_headdress',
		'item_fluffy_hat',
		'item_recipe_holy_locket',
		'item_energy_booster',

		'item_glimmer_cape',

		'item_ultimate_scepter_2',
		'item_aeon_disk',
		'item_recipe_aeon_pendant',

		'item_aghanims_shard',
		'item_wings_of_haste',
		'item_undying_heart',
		'item_insight_armor',
		'item_arcane_octarine_core',
		'item_sphere_2',
	},
	npc_dota_hero_oracle = {
		'item_headdress',
		'item_fluffy_hat',
		'item_recipe_holy_locket',
		'item_glimmer_cape',
		'item_aghanims_shard',
		'item_ultimate_scepter_2',
		'item_wings_of_haste',
		'item_arcane_octarine_core',
		'item_aeon_disk',
		'item_recipe_aeon_pendant',
	},
	npc_dota_hero_phantom_assassin = {
		'item_phase_boots',
		'item_arcane_boots',
		'item_tranquil_boots',
		'item_aghanims_shard',
		'item_desolator',
		'item_recipe_abyssal_blade',
		'item_wasp',
		'item_ultimate_scepter_2',
		'item_satanic',
		'item_vladmir_2',
		'item_excalibur',
	},
	npc_dota_hero_pudge = {
		'item_aghanims_shard',
		'item_blade_mail_2',
		'item_lotus_orb',

		'item_wings_of_haste',

		'item_voodoo_mask',
		'item_recipe_eternal_shroud',

		'item_radiance_2',
		'item_undying_heart',
		'item_insight_armor',
		'item_ultimate_scepter_2',
	},
	npc_dota_hero_sand_king = {
		'item_wings_of_haste',
		'item_aghanims_shard',
		'item_ultimate_orb',
		'item_ultimate_orb',
		'item_octarine_core',
		'item_recipe_arcane_octarine_core',
		'item_undying_heart',
	},
	npc_dota_hero_skywrath_mage = {
		'item_aghanims_shard',
		'item_ultimate_orb',
		'item_ultimate_orb',
		'item_magic_scepter',
		'item_wings_of_haste',
		'item_dagon_5',
		'item_arcane_octarine_core',
		'item_hallowed_scepter',
	},
	npc_dota_hero_sniper = {
		'item_hyperstone',
		'item_recipe_mjollnir',
		'item_wings_of_haste',
		'item_aghanims_shard',
		'item_ultimate_scepter_2',
		'item_monkey_king_bar_2',
		'item_wasp',
		'item_skadi',
	},
	npc_dota_hero_sven = {
		'item_wings_of_haste',
		'item_aghanims_shard',
		'item_ultimate_scepter_2',
		'item_reaver',
		'item_recipe_overwhelming_blink',
		'item_undying_heart',
		'item_wasp',
		'item_vladmir_2',
	},
	npc_dota_hero_tiny = {
		'item_aghanims_shard',
		'item_ultimate_scepter_2',
		'item_undying_heart',
	},
	npc_dota_hero_vengefulspirit = {
		'item_aghanims_shard',
		'item_ultimate_scepter_2',
		'item_wasp',
	},
	npc_dota_hero_viper = {
		'item_aghanims_shard',
		'item_wings_of_haste',
		
		'item_javelin',
		'item_javelin',
		'item_recipe_monkey_king_bar_2',
		'item_ultimate_orb',
		'item_ultimate_orb',
		'item_wasp',

		'item_skadi',
		'item_moon_shard_datadriven',
	},
	npc_dota_hero_windrunner = {
		'item_aghanims_shard',
		'item_wings_of_haste',
		'item_javelin',
		'item_javelin',
		'item_recipe_monkey_king_bar_2',
		'item_ultimate_orb',
		'item_ultimate_orb',
		'item_hallowed_scepter',
		'item_wasp',
		'item_moon_shard_datadriven',
	},
	npc_dota_hero_witch_doctor = {
		'item_aghanims_shard',
		'item_ultimate_orb',
		'item_ultimate_orb',

		'item_hallowed_scepter',
		'item_arcane_octarine_core',
		'item_sphere_2',
	},
	npc_dota_hero_skeleton_king = {
		'item_aghanims_shard',
		'item_wings_of_haste',
		'item_ultimate_scepter_2',
		
		'item_javelin',
		'item_javelin',
		'item_recipe_monkey_king_bar_2',
		'item_reaver',
		'item_recipe_overwhelming_blink',

		'item_undying_heart',
		'item_wasp',
		'item_moon_shard_datadriven',
	},
	npc_dota_hero_zuus = {
		'item_null_talisman',
		'item_null_talisman',
		'item_soul_booster',
		'item_recipe_aether_lens',
		'item_recipe_aether_lens',
		'item_aghanims_shard',
		'item_veil_of_discord',
		'item_recipe_arcane_octarine_core',
		'item_ultimate_scepter_2',
		'item_hallowed_scepter',

		'item_wings_of_haste',
	},
}



tBotItemData.sellItemList = {
	npc_dota_hero_axe = {
		'item_bracer',
		'item_magic_wand',
		'item_tranquil_boots',
	},
	npc_dota_hero_nevermore = {
		'item_magic_wand',
		'item_wraith_band',
		'item_bottle',
		'item_power_treads',
	},
	npc_dota_hero_bane = {
		'item_magic_wand',
		'item_null_talisman',
		'item_phase_boots',
	},
	npc_dota_hero_bounty_hunter = {
		'item_magic_wand',
		'item_medallion_of_courage',
		'item_ancient_janggo',
		'item_phase_boots',
	},
	npc_dota_hero_bloodseeker = {
		'item_magic_wand',
		'item_quelling_blade',
		'item_wraith_band',
		'item_wraith_band',
		'item_power_treads',
	},
	npc_dota_hero_bristleback = {
		'item_magic_wand',
		'item_vanguard',
	},
	npc_dota_hero_chaos_knight = {
		'item_magic_wand',
		'item_crown',
		'item_ancient_janggo',
		'item_power_treads',
	},
	npc_dota_hero_crystal_maiden = {
		'item_magic_wand',
		'item_phase_boots',
	},
	npc_dota_hero_dazzle = {
		'item_arcane_boots',
		'item_urn_of_shadows',
	},
	npc_dota_hero_death_prophet = {
		'item_null_talisman',
		'item_phase_boots',
	},
	npc_dota_hero_dragon_knight = {
	},
	npc_dota_hero_drow_ranger = {
		'item_branches',
		'item_wraith_band',
		'item_power_treads',
		'item_mask_of_madness',
	},

	npc_dota_hero_earthshaker = {
		'item_magic_wand',
		'item_wraith_band',
		'item_arcane_boots',
		'item_cyclone',
	},
	npc_dota_hero_jakiro = {
		'item_magic_wand',
		'item_ring_of_basilius',
		'item_arcane_boots',
	},
	npc_dota_hero_juggernaut = {
		'item_wraith_band',
		'item_wraith_band',
		'item_phase_boots',
	},
	npc_dota_hero_kunkka = {
		'item_magic_wand',
		'item_phase_boots',
		'item_ancient_janggo',
	},
	npc_dota_hero_lich = {
		'item_tranquil_boots',
	},
	npc_dota_hero_lina = {
		'item_magic_wand',
		'item_arcane_boots',
	},
	npc_dota_hero_lion = {
		'item_null_talisman',
		'item_tranquil_boots',
	},
	npc_dota_hero_luna = {
		'item_ring_of_protection',
		'item_magic_wand',
		'item_wraith_band',
		'item_ring_of_basilius',
		'item_power_treads',
	},
	npc_dota_hero_necrolyte = {
		'item_null_talisman',
	},
	npc_dota_hero_omniknight = {
		'item_ring_of_basilius',
		'item_arcane_boots',
	},
	npc_dota_hero_oracle = {
		'item_arcane_boots',
	},
	npc_dota_hero_phantom_assassin = {
		'item_magic_wand',
	},
	npc_dota_hero_pudge = {
		'item_magic_wand',
		'item_bracer',
		'item_bottle',
		'item_tranquil_boots',
	},
	npc_dota_hero_sand_king = {
		'item_branches',
		'item_arcane_boots',
	},
	npc_dota_hero_skywrath_mage = {
		'item_magic_wand',
		'item_null_talisman',
		'item_arcane_boots',
		'item_cyclone',
	},
	npc_dota_hero_sniper = {
		'item_magic_wand',
		'item_wraith_band',
	},
	npc_dota_hero_sven = {
		'item_quelling_blade',
		'item_magic_wand',
		'item_power_treads',
	},
	npc_dota_hero_tiny = {
	},
	npc_dota_hero_vengefulspirit = {
	},
	npc_dota_hero_viper = {
		'item_wraith_band',
		'item_ring_of_basilius',
		'item_power_treads',
	},
	npc_dota_hero_windrunner = {
		'item_null_talisman',
		'item_phase_boots',
	},
	npc_dota_hero_witch_doctor = {
		'item_magic_wand',
	},
	npc_dota_hero_skeleton_king = {
		'item_quelling_blade',
		'item_magic_wand',
		'item_power_treads',
		'item_echo_sabre',
		'item_armlet',
	},
	npc_dota_hero_zuus = {
		'item_null_talisman',
		'item_null_talisman',
		'item_arcane_boots',
	},
}



tBotItemData.itemConsumableList = {
	'item_tango_single',
	'item_tango',
	'item_clarity',
	'item_faerie_fire',
	'item_enchanted_mango',
	'item_flask',
}

tBotItemData.itemConsumeList = {
	'item_wings_of_haste',
	'item_ultimate_scepter_2',
	'item_moon_shard_datadriven',
}
