name: Create Release PR
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release version like v3.00"
        required: true

jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Reset promotion branch
        run: |
          git fetch origin develop:develop
          git reset --hard develop

      - name: Check if PR exist_pr_number
        id: check_pr
        run: |
          pr_number=$(gh pr list --base main --head develop --json number -q '.[0].number')
          echo exist_pr_number=$pr_number >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pull Request
        id: cpr
        if: steps.check_pr.outputs.exists == ''
        uses: peter-evans/create-pull-request@v7
        with:
          title: ${{ github.event.inputs.version }}
          body: |
            ## Checklist

            - [ ] 更新游戏版本号

            ## Release Note

            [b]游戏性更新 ${{ github.event.inputs.version }}[/b]

            修正一些bug和平衡性改动。

            [b]Gameplay update ${{ github.event.inputs.version }}[/b]

            Fixed some bug and balance.
          branch: develop
          base: main
          reviewers: windybirth
          labels: release
          draft: true

      - name: Ready Pull Request
        run: gh pr ready ${{ steps.cpr.outputs.pull-request-number }}
        env:
          GITHUB_TOKEN: ${{ secrets.WINDY_PR_PAT }}

      - name: Enable Pull Request Automerge
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.WINDY_PR_PAT }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: merge
